name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: setup-ros2
        run: |
          sudo apt update
          sudo apt install -y curl gnupg2 lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions
      - name: build and test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ..
          mkdir -p ros2_ws/src
          # リポジトリをワークスペースに移動してビルド
          mv rs_tasks ros2_ws/src/mypkg
          cd ros2_ws
          colcon build
